version: "3"

services:
  static:
    container_name: frontinbh_static
    build: .
    ports:
      - "8080:80"
    
  server:
    working_dir: /usr/src/app
    container_name: frontinbh_server
    image: mhart/alpine-node:latest
    volumes:
      - ./server:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start